### ISSUE TITLE
server-side Swift compatibility

### ISSUE THREAD

**Issue by skreutzberger** [SwiftyBeaver/SwiftyBeaver#154]
Parts of the framework are not fully working with Swift on Ubuntu. The work is done on a separate feature branch.

**Tasks:**

- [x]  Migrate AES256CBC class to server-side Swift
- [x]  Introduce new folder structure for tests
- [x]  Migrate the remaining classes
- [x]  Fix nasty SBPlatformDestination issue
- [x]  Test in a real-life server-side Swift project like SBWebsite
- [x]  Merge with master branch and release new version

**Comment by skreutzberger** [comment]
It seems the issue is not in the platform but in Vapor?!
